services:
  postgres:
    image: postgres:15.3
    user: postgres
    command: -c jit=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev_journal_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - dev_journal_postgres:/var/lib/postgresql/data
    networks:
      - dev_journal_network

volumes:
  dev_journal_postgres:

networks:
  dev_journal_network:
